use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    // Rebuild if any component changes or global.css changes
    println!("cargo:rerun-if-changed=src/components");
    println!("cargo:rerun-if-changed=global.css");
    println!("cargo:rerun-if-changed=blog");

    // Generate src/blog_posts.rs with a compile-time slug → content lookup
    let blog_dir = Path::new("blog");
    let out = Path::new("src/blog_posts.rs");

    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(dir) = fs::read_dir(blog_dir) {
        for entry in dir.flatten() {
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if name.ends_with(".md") {
                let slug = name.trim_end_matches(".md").to_string();
                let rel_path = format!("../blog/{}", name);
                entries.push((slug, rel_path));
            }
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::from(
        "// AUTO-GENERATED by build.rs — do not edit manually\n\
         pub fn get_post_content(slug: &str) -> Option<&'static str> {\n\
             match slug {\n",
    );
    for (slug, path) in &entries {
        code.push_str(&format!(
            "        \"{}\" => Some(include_str!(\"{}\")),\n",
            slug, path
        ));
    }
    code.push_str("        _ => None,\n    }\n}\n");

    fs::write(out, code).expect("Failed to write src/blog_posts.rs");

    let status = Command::new("npx")
        .args([
            "--yes",
            "tailwindcss@3.4.17",
            "-i",
            "./global.css",
            "-o",
            "./public/styles.css",
            "--minify",
        ])
        .status()
        .expect("Failed to build your CSS");

    if !status.success() {
        panic!("Build Script execution failed");
    }
}
