[package]
name = "elcharitas"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
google-fonts = "0.1"
lazy_static = "1.5"
ngyn = { git = "https://github.com/ngyn-rs/ngyn", branch = "dev" }
simple-rsx = { git = "https://github.com/elcharitas/simple-rsx", branch = "main" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
url = "2.5"
