[package]
name = "elcharitas"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
google-fonts = "0.1"
lazy_static = "1.5"
ngyn = { version = "0.5.4" }
momenta = { version = "0.2", git = "https://github.com/elcharitas/momenta.git", branch = "main" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5"
