name = "elcharitas-new"
type = "javascript"
main = "build/elcharitas_new.js"
account_id = "a1a3f41fdca34f8949f1933ee43d6323"
workers_dev = true
compatibility_date = "2024-12-16"

routes = [
  { pattern = "example.com/*", zone_name = "example.com" }
]

[env.production]
name = "elcharitas-wtf-prod"
routes = [
  { pattern = "elcharitas.wtf/*", zone_name = "elcharitas.wtf" }
]
vars = { ENVIRONMENT = "production", HASHNODE_PUBLICATION_HOST = "blog.elcharitas.wtf" }

[env.staging]
name = "elcharitas-wtf-staging"
routes = [
  { pattern = "staging.elcharitas.wtf/*", zone_name = "elcharitas.wtf" }
]
vars = { ENVIRONMENT = "staging" }

[build]
cwd = "./"
upload = { format = "modules", dir = "build" }
