name = "elcharitas-new"
main = "build/elcharitas_new.js"
account_id = "a1a3f41fdca34f8949f1933ee43d6323"
workers_dev = true
compatibility_date = "2024-12-16"

routes = [
  { pattern = "elcharitas.wtf/*", zone_name = "elcharitas.wtf" }
]
vars = { ENVIRONMENT = "production", HASHNODE_PUBLICATION_HOST = "elcharitas.wtf/blog", ORCID_ID = "0009-0006-6802-6663" }

[[kv_namespaces]]
binding = "NEWSLETTER_SUBSCRIBERS"
id = "6eba1c9c02d44614ad60b5ac668aab87"

[triggers]
crons = ["0 9 * * 5"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
